version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 3002:3002
    depends_on:
      - mongo
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  mongo:
    image: mongo
    ports:
      - 27018:27017
