# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the working directory
COPY frontend/package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend code
COPY frontend/ .

# Expose the port on which your frontend is running
EXPOSE 3000

# Start the frontend server
CMD ["npm", "start"]
