# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app/backend

# Copy package.json and package-lock.json to the working directory
COPY backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy the rest of the backend code
COPY backend/ .

# Expose the port on which your backend is running
EXPOSE 3002

# Start the backend server
CMD ["npm", "start"]
